[package]
name = "transaction-cache"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.6.0"
dotenvy = "0.15.7"
futures = "0.3.31"
log = "0.4.29"
serde = "1.0.228"
serde_json = "1.0.145"
solana-client = "3.1.4"
solana-sdk = "3.0.0"
solana-transaction-status-client-types = "3.1.4"
solana-tx-parser = { version = "0.1.0", path = "../solana-tx-parser" }
tokio = "1.48.0"
utils = { version = "0.1.0", path = "../utils" }
anyhow = "1.0.100"
